=== cash2one/s-core/s-auto/src/main/resources/config.xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="project" type="projectType"/>
    <xs:complexType name="post-parameterType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="optional"/>
                <xs:attribute type="xs:string" name="value" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="ftp-testType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="login" use="optional"/>
                <xs:attribute type="xs:string" name="password" use="optional"/>
                <xs:attribute type="xs:string" name="host" use="optional"/>
                <xs:attribute type="xs:string" name="message" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="check-email-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="login" use="optional"/>
                <xs:attribute type="xs:string" name="password" use="optional"/>
                <xs:attribute type="xs:string" name="host" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="post-request-commandType">
        <xs:sequence>
            <xs:element type="post-parametersType" name="post-parameters"/>
            <xs:element type="extract-commandsType" name="extract-commands" minOccurs="0"/>
            <xs:element type="test-commandsType" name="test-commands" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="url" use="required"/>
        <xs:attribute type="xs:string" name="referer"/>
    </xs:complexType>
    <xs:complexType name="commandsType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="anti-captcha-commandType" name="anti-captcha-command"/>
            <xs:element type="check-email-commandType" name="check-email-command" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="check-ftp-account-commandType" name="check-ftp-account-command"/>
            <xs:element type="delete-email-commandType" name="delete-email-command"/>
            <xs:element type="email-commandType" name="email-command"/>
            <xs:element type="generate-string-commandType" name="generate-string-command"/>
            <xs:element type="generate-time-commandType" name="generate-time-command"/>
            <xs:element type="generate-number-commandType" name="generate-number-command"/>
            <xs:element type="load-email-commandType" name="load-email-command"/>
            <xs:element type="load-ftp-account-commandType" name="load-ftp-account-command"/>
            <xs:element type="xs:string" name="load-useragent-command"/>
            <xs:element type="load-proxy-commandType" name="load-proxy-command"/>
            <xs:element type="get-request-commandType" name="get-request-command"/>
            <xs:element type="save-image-commandType" name="save-image-command"/>
            <xs:element type="recaptcha-commandType" name="recaptcha-command"/>
            <xs:element type="post-request-commandType" name="post-request-command"/>
            <xs:element type="save-blog-commandType" name="save-blog-command"/>
            <xs:element type="save-email-commandType" name="save-email-command"/>
            <xs:element type="save-ftp-account-commandType" name="save-ftp-account-command"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="extract-commandsType">
        <xs:sequence>
            <xs:element type="extract-regexp-variableType" name="extract-regexp-variable" maxOccurs="unbounded"
                        minOccurs="0"/>
            <xs:element type="extract-xpath-variableType" name="extract-xpath-variable" maxOccurs="unbounded"
                        minOccurs="0"/>
            <xs:element type="extract-attr-value-variableType" name="extract-attr-value-variable" maxOccurs="unbounded"
                        minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="projectType">
        <xs:sequence>
            <xs:element type="commandsType" name="commands"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="save-image-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name"/>
                <xs:attribute type="xs:string" name="url"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="test-commandsType">
        <xs:sequence>
            <xs:element type="string-testType" name="string-test" minOccurs="0"/>
            <xs:element type="ftp-testType" name="ftp-test" minOccurs="0"/>
            <xs:element type="email-testType" name="email-test" minOccurs="0"/>
            <xs:element type="element-testType" name="element-test" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="save-blog-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="login" use="required"/>
                <xs:attribute type="xs:string" name="password" use="required"/>
                <xs:attribute type="xs:string" name="url" use="required"/>
                <xs:attribute type="xs:string" name="type" use="required"/>
                <xs:attribute type="xs:string" name="xmlrpc" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="get-request-commandType">
        <xs:sequence>
            <xs:element type="extract-commandsType" name="extract-commands" minOccurs="0"/>
            <xs:element type="test-commandsType" name="test-commands" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="url" use="required"/>
        <xs:attribute type="xs:string" name="referer"/>
    </xs:complexType>
    <xs:complexType name="extract-xpath-variableType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="query" use="required"/>
                <xs:attribute type="xs:string" name="field" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="delete-email-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="email"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="check-ftp-account-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="login"/>
                <xs:attribute type="xs:string" name="password"/>
                <xs:attribute type="xs:string" name="host"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="load-proxy-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="key"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="load-email-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="prefix"/>
                <xs:attribute type="xs:string" name="host"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="extract-attr-value-variableType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="attribute" use="required"/>
                <xs:attribute type="xs:string" name="value" use="required"/>
                <xs:attribute type="xs:string" name="field" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="save-ftp-account-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="url" use="required"/>
                <xs:attribute type="xs:string" name="login" use="required"/>
                <xs:attribute type="xs:string" name="password" use="required"/>
                <xs:attribute type="xs:string" name="host" use="required"/>
                <xs:attribute type="xs:string" name="prefix" use="required"/>
                <xs:attribute type="xs:string" name="type" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="generate-string-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="minSize" use="required"/>
                <xs:attribute type="xs:string" name="maxSize" use="required"/>
                <xs:attribute type="xs:string" name="appendDigits"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="generate-time-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="generate-number-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="min" use="required"/>
                <xs:attribute type="xs:string" name="max" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="anti-captcha-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="optional"/>
                <xs:attribute type="xs:string" name="image" use="optional"/>
                <xs:attribute type="xs:string" name="ext" use="optional"/>
                <xs:attribute type="xs:string" name="phrase" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="post-parametersType">
        <xs:sequence>
            <xs:element type="post-parameterType" name="post-parameter" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="load-ftp-account-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="prefix"/>
                <xs:attribute type="xs:string" name="type"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="save-email-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="email" use="required"/>
                <xs:attribute type="xs:string" name="host" use="required"/>
                <xs:attribute type="xs:string" name="user" use="required"/>
                <xs:attribute type="xs:string" name="password" use="required"/>
                <xs:attribute type="xs:string" name="type" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="extract-regexp-variableType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="pattern" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="recaptcha-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="url" use="required"/>
                <xs:attribute type="xs:string" name="image" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="string-testType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="value" use="required"/>
                <xs:attribute type="xs:string" name="expected"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="email-testType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="login" use="required"/>
                <xs:attribute type="xs:string" name="password" use="required"/>
                <xs:attribute type="xs:string" name="host" use="required"/>
                <xs:attribute type="xs:string" name="message"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="element-testType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="attribute" use="required"/>
                <xs:attribute type="xs:string" name="value" use="required"/>
                <xs:attribute type="xs:string" name="expected"/>
                <xs:attribute type="xs:string" name="message"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="email-commandType" mixed="true">
        <xs:sequence>
            <xs:element type="extract-commandsType" name="extract-commands" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="login" use="required"/>
        <xs:attribute type="xs:string" name="password" use="required"/>
        <xs:attribute type="xs:string" name="host" use="required"/>
        <xs:attribute type="xs:string" name="sleep" use="required"/>
        <xs:attribute type="xs:string" name="attempts" use="required"/>
    </xs:complexType>
</xs:schema>

=== cash2one/s-core/s-auto/doc/conf/livejournal.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../src/main/resources/config.xml.xsd">
    <commands>
        <load-useragent-command/>
        <load-proxy-command key="livejournal"/>

        <load-email-command prefix="email" host="pop.yandex.ru"/>

        <get-request-command url="https://www.livejournal.com/create.bml" referer="http://www.livejournal.com/">
            <extract-commands>
                <extract-regexp-variable name="recaptcha_url1"
                                         pattern="&quot;(https://api-secure.recaptcha.net/challenge.+?)&quot;"/>
                <extract-attr-value-variable name="form_auth" attribute="name" value="lj_form_auth" field="value"/>
            </extract-commands>
        </get-request-command>

        <recaptcha-command name="recaptcha_challenge1" url="${recaptcha_url1}" image="recaptcha_response1"/>

        <generate-string-command name="login" minSize="10" maxSize="14"/>
        <generate-string-command name="password" minSize="6" maxSize="8" appendDigits="true"/>
        <generate-number-command name="bday_dd" min="10" max="28"/>
        <generate-number-command name="bday_mm" min="1" max="12"/>
        <generate-number-command name="bday_yyyy" min="1970" max="1990"/>


        <post-request-command url="https://www.livejournal.com/create.bml" referer="https://www.livejournal.com/create.bml">
            <post-parameters>
                <post-parameter name="Widget[CreateAccount]_bday_dd" value="${bday_dd}"/>
                <post-parameter name="Widget[CreateAccount]_bday_mm" value="${bday_mm}"/>
                <post-parameter name="Widget[CreateAccount]_bday_yyyy" value="${bday_yyyy}"/>
                <post-parameter name="Widget[CreateAccount]_email" value="${email}"/>
                <post-parameter name="Widget[CreateAccount]_password1" value="${password}"/>
                <post-parameter name="Widget[CreateAccount]_password2" value="${password}"/>
                <post-parameter name="Widget[CreateAccount]_gender" value="M"/>
                <post-parameter name="Widget[CreateAccount]_setLiveId" value="no"/>
                <post-parameter name="Widget[CreateAccount]_submit" value="Create Account"/>
                <post-parameter name="Widget[CreateAccount]_user" value="${login}"/>
                <post-parameter name="lj_form_auth" value="${form_auth}"/>
                <post-parameter name="recaptcha_challenge_field" value="${recaptcha_challenge1}"/>
                <post-parameter name="recaptcha_response_field" value="${recaptcha_response1}"/>
            </post-parameters>
            <test-commands>
                <string-test value="create/step2"/>
            </test-commands>
        </post-request-command>
        <email-command login="${emaillogin}" password="${emailpassword}" host="${emailhost}" sleep="25000" attempts="5">
            <extract-commands>
                <extract-regexp-variable name="activate_url" pattern="(http://www\.livejournal\.com/confirm/.+)$"/>
            </extract-commands>
        </email-command>

        <get-request-command url="${activate_url}"/>
        <save-blog-command login="${login}" password="${password}" url="http://${login}.livejournal.com"
                           type="livejournal"
                           xmlrpc="http://www.livejournal.com/interface/xmlrpc"/> 
    </commands>
</project>

=== cash2one/s-core/s-auto/trunk/doc/conf/zxq.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../src/main/resources/config.xml.xsd">
    <commands>
        <load-useragent-command/>

        <get-request-command url="http://zymic.com/"/>

        <post-request-command url="http://zymic.com/backend/login_process.php" referer="http://zymic.com/">
            <post-parameters>
                <post-parameter name="username" value="testtest123"/>
                <post-parameter name="password" value="fakepass1"/>
                <post-parameter name="persist-session" value="on"/>
                <post-parameter name="submit-form" value="Login"/>
            </post-parameters>
        </post-request-command>

        <get-request-command url="http://www.zymic.com/register-website/" referer="http://zymic.com/">

        </get-request-command>

        <post-request-command url="http://www.zymic.com/register-website/" referer="http://www.zymic.com/register-website/">
            <post-parameters>
                <post-parameter name="sitename" value="lkdjfglsjdg1234"/>
                <post-parameter name="domain" value="1"/>
            </post-parameters>
        </post-request-command>

        <get-request-command url="http://www.zymic.com/register-website/step2/" referer="http://www.zymic.com/register-website/">

        </get-request-command>

        <post-request-command url="http://www.zymic.com/register-website/step2/" referer="http://www.zymic.com/register-website/step2/">
            <post-parameters>
                <post-parameter name="password" value="fakepass1"/>
                <post-parameter name="passwordv" value="fakepass1"/>
            </post-parameters>
        </post-request-command>

        <get-request-command url="http://www.zymic.com/register-website/step3/" referer="http://www.zymic.com/register-website/step2/">
            <extract-commands>
                <extract-regexp-variable name="recaptcha_url1"
                                         pattern="&quot;(http://api.recaptcha.net/challenge.+?)&quot;"/>

            </extract-commands>
        </get-request-command>

        <recaptcha-command name="recaptcha_challenge1" url="${recaptcha_url1}" image="recaptcha_response1"/>

        <post-request-command url="http://www.zymic.com/register-website/step3#form" referer="http://www.zymic.com/register-website/step3">
            <post-parameters>
                <post-parameter name="agree1" value="on"/>
                <post-parameter name="agree2" value="on"/>
                <post-parameter name="agree3" value="on"/>
                <post-parameter name="recaptcha_challenge_field" value="${recaptcha_challenge1}"/>
                <post-parameter name="recaptcha_response_field" value="${recaptcha_response1}"/>
            </post-parameters>
        </post-request-command>

    </commands>
</project>
