=== cash2one/s-core/s-auto/src/main/resources/config.xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="project" type="projectType"/>
    <xs:complexType name="post-parameterType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="optional"/>
                <xs:attribute type="xs:string" name="value" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="ftp-testType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="login" use="optional"/>
                <xs:attribute type="xs:string" name="password" use="optional"/>
                <xs:attribute type="xs:string" name="host" use="optional"/>
                <xs:attribute type="xs:string" name="message" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="check-email-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="login" use="optional"/>
                <xs:attribute type="xs:string" name="password" use="optional"/>
                <xs:attribute type="xs:string" name="host" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="post-request-commandType">
        <xs:sequence>
            <xs:element type="post-parametersType" name="post-parameters"/>
            <xs:element type="extract-commandsType" name="extract-commands" minOccurs="0"/>
            <xs:element type="test-commandsType" name="test-commands" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="url" use="required"/>
        <xs:attribute type="xs:string" name="referer"/>
    </xs:complexType>
    <xs:complexType name="commandsType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="anti-captcha-commandType" name="anti-captcha-command"/>
            <xs:element type="check-email-commandType" name="check-email-command" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="check-ftp-account-commandType" name="check-ftp-account-command"/>
            <xs:element type="delete-email-commandType" name="delete-email-command"/>
            <xs:element type="email-commandType" name="email-command"/>
            <xs:element type="generate-string-commandType" name="generate-string-command"/>
            <xs:element type="generate-time-commandType" name="generate-time-command"/>
            <xs:element type="generate-number-commandType" name="generate-number-command"/>
            <xs:element type="load-email-commandType" name="load-email-command"/>
            <xs:element type="load-ftp-account-commandType" name="load-ftp-account-command"/>
            <xs:element type="xs:string" name="load-useragent-command"/>
            <xs:element type="load-proxy-commandType" name="load-proxy-command"/>
            <xs:element type="get-request-commandType" name="get-request-command"/>
            <xs:element type="save-image-commandType" name="save-image-command"/>
            <xs:element type="recaptcha-commandType" name="recaptcha-command"/>
            <xs:element type="post-request-commandType" name="post-request-command"/>
            <xs:element type="save-blog-commandType" name="save-blog-command"/>
            <xs:element type="save-email-commandType" name="save-email-command"/>
            <xs:element type="save-ftp-account-commandType" name="save-ftp-account-command"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="extract-commandsType">
        <xs:sequence>
            <xs:element type="extract-regexp-variableType" name="extract-regexp-variable" maxOccurs="unbounded"
                        minOccurs="0"/>
            <xs:element type="extract-xpath-variableType" name="extract-xpath-variable" maxOccurs="unbounded"
                        minOccurs="0"/>
            <xs:element type="extract-attr-value-variableType" name="extract-attr-value-variable" maxOccurs="unbounded"
                        minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="projectType">
        <xs:sequence>
            <xs:element type="commandsType" name="commands"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="save-image-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name"/>
                <xs:attribute type="xs:string" name="url"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="test-commandsType">
        <xs:sequence>
            <xs:element type="string-testType" name="string-test" minOccurs="0"/>
            <xs:element type="ftp-testType" name="ftp-test" minOccurs="0"/>
            <xs:element type="email-testType" name="email-test" minOccurs="0"/>
            <xs:element type="element-testType" name="element-test" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="save-blog-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="login" use="required"/>
                <xs:attribute type="xs:string" name="password" use="required"/>
                <xs:attribute type="xs:string" name="url" use="required"/>
                <xs:attribute type="xs:string" name="type" use="required"/>
                <xs:attribute type="xs:string" name="xmlrpc" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="get-request-commandType">
        <xs:sequence>
            <xs:element type="extract-commandsType" name="extract-commands" minOccurs="0"/>
            <xs:element type="test-commandsType" name="test-commands" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="url" use="required"/>
        <xs:attribute type="xs:string" name="referer"/>
    </xs:complexType>
    <xs:complexType name="extract-xpath-variableType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="query" use="required"/>
                <xs:attribute type="xs:string" name="field" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="delete-email-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="email"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="check-ftp-account-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="login"/>
                <xs:attribute type="xs:string" name="password"/>
                <xs:attribute type="xs:string" name="host"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="load-proxy-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="key"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="load-email-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="prefix"/>
                <xs:attribute type="xs:string" name="host"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="extract-attr-value-variableType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="attribute" use="required"/>
                <xs:attribute type="xs:string" name="value" use="required"/>
                <xs:attribute type="xs:string" name="field" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="save-ftp-account-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="url" use="required"/>
                <xs:attribute type="xs:string" name="login" use="required"/>
                <xs:attribute type="xs:string" name="password" use="required"/>
                <xs:attribute type="xs:string" name="host" use="required"/>
                <xs:attribute type="xs:string" name="prefix" use="required"/>
                <xs:attribute type="xs:string" name="type" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="generate-string-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="minSize" use="required"/>
                <xs:attribute type="xs:string" name="maxSize" use="required"/>
                <xs:attribute type="xs:string" name="appendDigits"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="generate-time-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="generate-number-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="min" use="required"/>
                <xs:attribute type="xs:string" name="max" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="anti-captcha-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="optional"/>
                <xs:attribute type="xs:string" name="image" use="optional"/>
                <xs:attribute type="xs:string" name="ext" use="optional"/>
                <xs:attribute type="xs:string" name="phrase" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="post-parametersType">
        <xs:sequence>
            <xs:element type="post-parameterType" name="post-parameter" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="load-ftp-account-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="prefix"/>
                <xs:attribute type="xs:string" name="type"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="save-email-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="email" use="required"/>
                <xs:attribute type="xs:string" name="host" use="required"/>
                <xs:attribute type="xs:string" name="user" use="required"/>
                <xs:attribute type="xs:string" name="password" use="required"/>
                <xs:attribute type="xs:string" name="type" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="extract-regexp-variableType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="pattern" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="recaptcha-commandType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="url" use="required"/>
                <xs:attribute type="xs:string" name="image" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="string-testType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="value" use="required"/>
                <xs:attribute type="xs:string" name="expected"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="email-testType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="login" use="required"/>
                <xs:attribute type="xs:string" name="password" use="required"/>
                <xs:attribute type="xs:string" name="host" use="required"/>
                <xs:attribute type="xs:string" name="message"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="element-testType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="attribute" use="required"/>
                <xs:attribute type="xs:string" name="value" use="required"/>
                <xs:attribute type="xs:string" name="expected"/>
                <xs:attribute type="xs:string" name="message"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="email-commandType" mixed="true">
        <xs:sequence>
            <xs:element type="extract-commandsType" name="extract-commands" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="login" use="required"/>
        <xs:attribute type="xs:string" name="password" use="required"/>
        <xs:attribute type="xs:string" name="host" use="required"/>
        <xs:attribute type="xs:string" name="sleep" use="required"/>
        <xs:attribute type="xs:string" name="attempts" use="required"/>
    </xs:complexType>
</xs:schema>

=== cash2one/s-core/s-core/doc/conf/narod.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../src/main/resources/config.xml.xsd">
    <commands>
        <load-useragent-command/>
        <load-proxy-command key="yandex"/>

        <generate-string-command name="login" minSize="8" maxSize="14" appendDigits="true"/>
        <generate-string-command name="password" minSize="6" maxSize="8" appendDigits="true"/>
        <generate-string-command name="iname" minSize="6" maxSize="10" appendDigits="false"/>
        <generate-string-command name="fname" minSize="6" maxSize="8" appendDigits="false"/>
        <generate-string-command name="answer" minSize="5" maxSize="10" appendDigits="false"/>

        <get-request-command
                url="http://passport.yandex.ru/passport?mode=auth&amp;from=narod&amp;retpath=http://narod.yandex.ru/"
                referer="http://narod.yandex.ru/">
            <extract-commands>
                <!--<extract-xpath-variable name="register_url" query="//div[@class='b-domik__link']/a" field="href"/>-->
                <extract-regexp-variable name="register_url"
                                         pattern="class=&quot;b-domik__link&quot; href=&quot;(.*)&quot; tabindex=&quot;30&quot;"/>
            </extract-commands>
        </get-request-command>

        <get-request-command url="${register_url}"
                             referer="http://passport.yandex.ru/passport?mode=auth&amp;from=narod&amp;retpath=http://narod.yandex.ru/">
            <extract-commands>
                <extract-attr-value-variable name="idkey" attribute="name" value="idkey" field="value"/>
                <extract-attr-value-variable name="steponeurl" attribute="name" value="bigForm" field="action"/>
            </extract-commands>
        </get-request-command>

        <post-request-command url="${steponeurl}"
                              referer="http://passport.yandex.ru/passport?mode=register&amp;msg=mail&amp;retpath=http%3A%2F%2Fnarod.yandex.ru%2F">
            <post-parameters>
                <post-parameter name="idkey" value="${idkey}"/>
                <post-parameter name="step" value="one"/>
                <post-parameter name="fresh" value="3"/>
                <post-parameter name="filled" value="yes"/>
                <post-parameter name="iname" value="${iname}"/>
                <post-parameter name="fname" value="${fname}"/>
                <post-parameter name="login" value="${login}"/>
                <post-parameter name="done" value="Дальше →"/>
            </post-parameters>

            <extract-commands>
                <extract-attr-value-variable name="idkey" attribute="name" value="idkey" field="value"/>
                <extract-attr-value-variable name="imageurl" attribute="class" value="captcha-img" field="src"/>
                <extract-attr-value-variable name="steptwourl" attribute="name" value="bigForm" field="action"/>
            </extract-commands>
        </post-request-command>

        <save-image-command name="imagedata" url="${imageurl}"/>

        <anti-captcha-command name="captcha_response" image="${imagedata}" ext="gif" phrase="false"/>

        <generate-time-command name="current_time"/>

        <post-request-command url="${steptwourl}" referer="${steponeurl}">
            <post-parameters>
                <post-parameter name="idkey" value="${idkey}"/>
                <post-parameter name="step" value="two"/>
                <post-parameter name="filled" value="yes"/>
                <post-parameter name="login" value="${login}"/>
                <post-parameter name="fname" value="${fname}"/>
                <post-parameter name="iname" value="${iname}"/>
                <post-parameter name="time" value="${current_time}"/>
                <post-parameter name="gmt_offset" value="-120"/>
                <post-parameter name="passwd" value="${password}"/>
                <post-parameter name="passwd2" value="${password}"/>
                <post-parameter name="hintq" value="2"/>
                <post-parameter name="udhintq" value=""/>
                <post-parameter name="hinta" value="${answer}"/>
                <post-parameter name="hintasave" value="${answer}"/>
                <!--<post-parameter name="questnum" value=""/>-->
                <!--<post-parameter name="hintqsave" value=""/>-->
                <post-parameter name="email" value=""/>
                <post-parameter name="phonenumber" value=""/>
                <post-parameter name="code" value="${captcha_response}"/>
                <post-parameter name="agreed" value="yes"/>
                <!--<post-parameter name="newform" value="Зарегистрировать"/>-->
            </post-parameters>
            <test-commands>
                <element-test attribute="class" value="b-error" expected="false"
                              message="account registered successfully"/>
            </test-commands>
        </post-request-command>
        <get-request-command
                url="http://passport.yandex.ru/passport?mode=auth&amp;msg=narod&amp;retpath=http://narod.yandex.ru/"
                referer="http://narod.yandex.ru/">
        </get-request-command>

        <generate-time-command name="timestamp"/>

        <post-request-command url="https://passport.yandex.ru/passport?mode=auth"
                              referer="http://passport.yandex.ru/passport?mode=auth&amp;msg=narod&amp;retpath=http://narod.yandex.ru/">
            <post-parameters>
                <post-parameter name="idkey" value="${idkey}"/>
                <post-parameter name="login" value="${login}"/>
                <post-parameter name="passwd" value="${password}"/>
                <post-parameter name="timestamp" value="${timestamp}"/>
                <post-parameter name="retpath" value="http://narod.yandex.ru/"/>
            </post-parameters>
        </post-request-command>

        <get-request-command url="http://mail.yandex.ru/">
            <test-commands>
                <email-test login="${login}" password="${password}" host="pop.yandex.ru"/>
            </test-commands>
        </get-request-command>

        <get-request-command url="http://narod.yandex.ru/">
            <extract-commands>
                <extract-attr-value-variable name="diskurl" attribute="class" value="button b-button-create"
                                             field="href"/>
            </extract-commands>
        </get-request-command>
        <get-request-command url="http://narod.yandex.ru${diskurl}" referer="http://narod.yandex.ru/">
            <test-commands>
                <ftp-test login="${login}" password="${password}" host="ftp.narod.ru"
                          message="ftp activated successfully"/>
            </test-commands>
        </get-request-command>


        <save-email-command email="${login}@yandex.ru" host="pop.yandex.ru" user="${login}" password="${password}"
                            type="yandex"/>
        <save-ftp-account-command url="http://${login}.narod.ru" login="${login}" password="${password}"
                                  host="ftp.narod.ru"
                                  prefix=""
                                  type="narod"/>
    </commands>
</project>

=== cash2one/s-core/s-core/doc/conf/qip.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../src/main/resources/config.xml.xsd">
    <commands>
        <load-useragent-command/>

        <load-proxy-command/>

        <get-request-command url="http://qip.ru/"/>

        <get-request-command url="http://qip.ru/reg/register" referer="http://qip.ru">
            <extract-commands>
                <extract-xpath-variable name="name_1" query="//form[@class='form']/span[last()]/input[1]" field="name"/>
                <extract-xpath-variable name="value_1" query="//form[@class='form']/span[last()]/input[1]" field="value"/>
                <extract-xpath-variable name="name_2" query="//form[@class='form']/span[last()]/input[2]" field="name"/>
                <extract-xpath-variable name="value_2" query="//form[@class='form']/span[last()]/input[2]" field="value"/>
                <extract-xpath-variable name="name_3" query="//form[@class='form']/span[last()]/input[3]" field="name"/>
                <extract-xpath-variable name="value_3" query="//form[@class='form']/span[last()]/input[3]" field="value"/>
            </extract-commands>
        </get-request-command>
    </commands>
</project>

=== cash2one/s-core/s-auto/trunk/src/main/resources/sample/commands.xml
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../config.xml.xsd">
    <commands>

        <anti-captcha-command name="captcha" image="${image_var}" ext="jpg" phrase="false"/>
        <check-email-command login="login" password="password" host="host"/>
        <check-email-command login="login" password="password" host="host"/>

        <check-ftp-account-command login="login" password="password" host="host"/>

        <delete-email-command email="test@asd.ru"/>

        <email-command login="${emaillogin}" password="${emailpassword}" host="${emailhost}" sleep="15000" attempts="5">
            <extract-commands>
                <extract-regexp-variable name="uid" pattern="(.+)"/>
                <extract-regexp-variable name="uid" pattern="(.+)"/>
                <extract-xpath-variable name="captchaurl" xpath="//user" value-field="value"/>
                <extract-attr-value-variable name="password" attribute="input" value="value" value-field="value"/>
            </extract-commands>
        </email-command>

        <anti-captcha-command name="captcha" image="${image_var}" ext="jpg" phrase="false"/>
        <generate-string-command name="string" minSize="5" maxSize="6" appendDigits="false"/>

        <load-email-command prefix="email" host="mail.clovermail.net"/>

        <load-ftp-account-command prefix="ftp_" type="narod"/>

        <load-useragent-command/>

        <load-proxy-command key="narod.ru"/>

        <get-request-command url="http://google.com" referrer="http://tut.by">
            <extract-commands>
                <extract-regexp-variable name="uid" pattern="(.+)"/>
                <extract-xpath-variable name="captchaurl" xpath="//user" value-field="value"/>
                <extract-xpath-variable name="captchaurl" xpath="//user" value-field="value"/>
                <extract-attr-value-variable name="password" attribute="input" value="value" value-field="value"/>
            </extract-commands>
        </get-request-command>

        <save-image-command name="firstimage" url="http://site.com/image.jpg"/>

        <recaptcha-command name="recaptcha_challenge1" url="${recaptcha_url1}" image="${recaptcha_response1}"/>

        <post-request-command url="${request-url-var}" referer="${ref-var}">
            <post-parameters>
                <post-parameter name="login" value="dwh"/>
                <post-parameter name="password" value="pass"/>
            </post-parameters>
            <extract-commands>
                <extract-regexp-variable name="uid" pattern="(.+)"/>
                <extract-xpath-variable name="captchaurl" xpath="//user" value-field="value"/>
                <extract-xpath-variable name="captchaurl" xpath="//user" value-field="value"/>
                <extract-xpath-variable name="captchaurl" xpath="//user" value-field="value"/>
                <extract-attr-value-variable name="password" attribute="input" value="value" value-field="value"/>
                <extract-attr-value-variable name="password" attribute="input" value="value" value-field="value"/>
            </extract-commands>
            <test-commands>
                <string-test value="Widget[Location]_country" expected="false"/>
                <ftp-test login="login" password="password" host="host" message="test failed"/>
                <ftp-test login="login" password="password" host="host" message="test failed"/>
                <email-test login="login" password="password" host="host" message="test failed"/>
            </test-commands>
        </post-request-command>

        <save-blog-command type="type" url="url" xmlrpc="xml" login="login" password="password"/>

        <save-email-command email="email" host="host" user="user" password="password" type="type"/>

        <save-ftp-account-command url="url" login="login" password="password" host="host" prefix="prefix" type="type"/>
    </commands>
</project>
